# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'mitterReactNativeStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mitterReactNativeStarter
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  target 'mitterReactNativeStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mitterReactNativeStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mitterReactNativeStarter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mitterReactNativeStarter-tvOS

end
